"""Initial schema: users, workers, patients, screenings, images, predictions, referrals, sync_events, locations, audit_logs

Revision ID: c55a112de338
Revises: 
Create Date: 2026-09-01 18:23:20.318793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55a112de338'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=50), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_district'), 'locations', ['district'], unique=False)
    op.create_index(op.f('ix_locations_village'), 'locations', ['village'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('worker_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role_type', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_workers_worker_code'), 'workers', ['worker_code'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_code', sa.String(length=50), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('pregnancy_status', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.create_index(op.f('ix_patients_village'), 'patients', ['village'], unique=False)
    op.create_table('sync_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(), nullable=True),
    sa.Column('synced_patients', sa.Integer(), nullable=True),
    sa.Column('synced_screenings', sa.Integer(), nullable=True),
    sa.Column('synced_referrals', sa.Integer(), nullable=True),
    sa.Column('conflicts_resolved', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('payload_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screenings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('screening_date', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('conjunctiva_quality', sa.Float(), nullable=True),
    sa.Column('nail_quality', sa.Float(), nullable=True),
    sa.Column('palm_quality', sa.Float(), nullable=True),
    sa.Column('overall_quality', sa.Float(), nullable=True),
    sa.Column('final_risk_category', sa.String(length=30), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenings_patient_id'), 'screenings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_screenings_worker_id'), 'screenings', ['worker_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screening_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('referral_facility', sa.String(length=150), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('lab_confirmed_hb', sa.Float(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('prescribed_treatment', sa.String(length=255), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id')
    )
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_table('screening_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screening_id', sa.String(length=36), nullable=False),
    sa.Column('site_type', sa.String(length=30), nullable=False),
    sa.Column('local_path', sa.String(length=255), nullable=True),
    sa.Column('cloud_path', sa.String(length=255), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('calibration_detected', sa.Boolean(), nullable=True),
    sa.Column('illumination_gain', sa.Float(), nullable=True),
    sa.Column('color_features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_images_screening_id'), 'screening_images', ['screening_id'], unique=False)
    op.create_table('screening_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screening_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('inference_timestamp', sa.DateTime(), nullable=True),
    sa.Column('conjunctiva_score', sa.Float(), nullable=True),
    sa.Column('nail_score', sa.Float(), nullable=True),
    sa.Column('palm_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_predictions')
    op.drop_index(op.f('ix_screening_images_screening_id'), table_name='screening_images')
    op.drop_table('screening_images')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_screenings_worker_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_patient_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_table('sync_events')
    op.drop_index(op.f('ix_patients_village'), table_name='patients')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_workers_worker_code'), table_name='workers')
    op.drop_table('workers')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_village'), table_name='locations')
    op.drop_index(op.f('ix_locations_district'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
